config/routes.rb
Rails.application.routes.draw do
  resources :sensors

  resources :buildings

  resources :sensor_data

  resources :devices

  resources :users

  resources :pages
  get 'home', to: 'pages#home'
  get 'faq', to: 'pages#faq'
  get 'buy', to: 'pages#buy'

  resources :sessions, only: [:create, :new]
  post 'sessions/destroy', to: 'sessions#destroy'
  get 'sessions/destroy', to: 'sessions#destroy'
  

  post 'first_contact/:address', to: "devices#first_contact"
  get  'first_contact/:address', to: "devices#first_contact"

  post 'sensor_data/batch_create/:device_address', to: 'sensor_data#batch_create'
  get 'sensor_data/batch_create/:device_address', to: 'sensor_data#batch_create'

  get 'buildings/:id/chart', to: 'buildings#chart'

  root 'pages#home'

end

app/models/device.rb
class Device < ActiveRecord::Base
	validates :encryption_key, presence: true
	validates :building_id, numericality: { only_integer: true, allow_nil: true }
	validates :address, uniqueness: true
	validates :name, presence: true

	#validates :user_id, numericality: { only_integer: true }
	belongs_to :building # This is the active building
	belongs_to :user
	has_many :device_buildings
	has_many :buildings, :through => :device_buildings

	def in_building?
		if self.building #not nil
			return self.building.active?
		else
			return false
		end
	end

	def checkout to_building_id
		if self.in_building? && (self.building_id != to_building_id)
			throw "Device #{id} in building"
		end
		self.building_id = to_building_id
		throw "Couldn't save device #{id}" if not self.save
	end

	def checkin building_id
		if building_id != self.building_id
			return true
		else
			self.building_id = nil
			return self.save
		end
	end

	 #This is slightly less ugly than the other way to do this
	alias_method :super_update, :update
	private :super_update
	def update(params)
		#Fail if it would change mid-building
		if in_building? && !params[building].nil? && params[building] != self.building_id
			return false
		end
		super_update(params)
	end

end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  force_ssl except: :first_contact unless Rails.env.development? || Rails.env.test?
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  skip_after_action :verify_authorized, :only => :first_contact
  skip_before_action :logged_out_redirect, only: :first_contact

  # GET /devices
  # GET /devices.json
  def index
    @devices = policy_scope(Device.where(user_id: current_user.id).page(params[:page]))
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new()
    authorize @device
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)
    authorize @device

    match = Device.find_by(address: @device.address)
    if match && User.find(match.user_id).admin?
      #Take the device from the admin and give it to the user.
      @device = match
      success = match.update(device_params)

    elsif User.find(@device.user_id).admin
      success = @device.save
    else
      flash.now[:error] = "Incorrect MAC address."
      success = false
    end

    respond_to do |format|
      if success
        format.html { redirect_to @device, notice: 'Sensor was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { @device = Device.new(device_params); render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update


    respond_to do |format|
      if @device.update(device_params)
        unless params[:device][:redirect_to].blank?
          redirect_to params[:device][:redirect_to]
          return
        end
        format.html { redirect_to @device, notice: 'Sensor was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Sensor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def first_contact
    @device = Device.find_by address: params[:address]

    #Don't authorize

    respond_to do |format|
      format.html { render(layout: false) }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_device
    @device = Device.find(params[:id])
    authorize @device
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def device_params
    params.require(:device).permit(:name, :address, :notes, :building_id, :encryption_key).merge(user_id: current_user.id)
  end
end

app/helpers/devices_helper.rb
module DevicesHelper

	def first_contact_string(device)
		string = Time.now.to_i.to_s + " "

		if @device.nil?
        	string << "<p>Device not found</p>"
		elsif @device.in_building?
			string << "In_Building: "
			string << device.building_id.to_s + " "

		else
			string << -1.to_s
		end
		return string
	end

	def get_sensors_string
	end

end

app/views/devices/_form.html.erb
<%# Expects to be handed a back_links variable, and a submit_name %>
<%= form_for(@device, html: {:class => "centered center-block"}) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :address, "MAC address" %><br>
    <% if @device.created_at.nil? || (current_user.admin?) %>
    <%= f.text_field :address %>
    <% else %>
    <%= @device.address %>
     <% end %>
  </div>
 
  <% if current_user.admin? %>
  <div class="field">
    <%= f.label :encryption_key %>
    <%= f.text_field :encryption_key, placeholder: "≤ 31 characters, no tabs, no spaces", value: @device.encryption_key || SecureRandom.base64(32)[0..30] %>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= back_links %>
    <%= f.submit submit_name%><%# #submit_name wouldn't be necessary if devices weren't called sensors %>
  </div>
<% end %>

app/views/devices/_form_remove_from_building.html.erb
<%= form_for(@device, html: { style: "display:inline-block" }) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation" style="display">
      <h2><%= pluralize(device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :redirect_to, :value => device_path(@device) %>
  <%= f.hidden_field :building_id, :value => nil %>

  <div class="actions" style="float:left; margin:0;">
    <%= f.submit "Remove"%>
  </div>
<% end %>

app/views/devices/edit.html.erb
<% provide :title, "Edit Device" %>

<% back_links = link_to('Cancel', devices_path)  +" | " + link_to('Show', @device) %>

<%= render 'form', back_links: back_links, submit_name: "Update Device" %>

app/views/devices/first_contact.html.erb
start
<%== ApplicationHelper::Vignere.encrypt( first_contact_string(@device), (@device.encryption_key if @device)) %>
end

app/views/devices/index.html.erb
<% provide :title, "Devices" %>

<p>A list of all devices. Click "New device" to add it onto the screen.</p>
<%= paginate @devices %>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>MAC Address</th>
      <th>Notes</th>
      <th>Current Building</th>
      <th colspan="3" class="options">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= link_to device.name, device %></td>
        <td><%= device.address %></td>
        <td><%== device.notes && device.notes.length > 20 ? h(device.notes.first(20)) + link_to("...", device) : device.notes %></td>
        <td><%= link_to(device.building.name, device.building) if device.in_building? && BuildingPolicy.new(current_user, device.building).show? %></td>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to('Destroy', device, method: :delete, data: { confirm: 'Are you sure?' }) if current_user.admin? %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @devices %>
<br>

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<% provide :title, "New Sensor" %>

<%= render 'form', back_links: link_to('Cancel', devices_path), submit_name: "Create Sensor" %>

app/views/devices/show.html.erb
<% provide :title, "Sensor View" %>

<p>
  <strong>Name:</strong>
  <%= @device.name %>
</p>

<% if @device.in_building? %>
  <p></p>
	<strong>Current Building:</strong>
	<%= link_to @device.building.name, @device.building %>
  (<%= render "form_remove_from_building" %>)
  <p></p>
<% end %>

<p>
  <strong>MAC Address:</strong>
  <%= @device.address %>
</p>

<div>
<strong>Notes:</strong>
  <pre><%= @device.notes %></pre>
<br>
</div>

<p>
  <strong>Past buildings:</strong>
  <ul>
  <% policy_scope(@device.device_buildings).order(created_at: :desc).each do |de| %>
    <% if de.building %>
    <li>
      <%= link_to de.building.name, de.building %> (<%= de.location.nil? ? "No location" : de.location %>)
    </li>
    <%end %>
  <% end %>
  </ul>
</p>

<%= link_to 'Back', devices_path %> |
<%= link_to 'Edit', edit_device_path(@device) %>