config/routes.rb
Rails.application.routes.draw do
  resources :sensors

  resources :buildings

  resources :sensor_data

  resources :devices

  resources :users

  resources :pages
  get 'home', to: 'pages#home'
  get 'faq', to: 'pages#faq'
  get 'buy', to: 'pages#buy'

  resources :sessions, only: [:create, :new]
  post 'sessions/destroy', to: 'sessions#destroy'
  get 'sessions/destroy', to: 'sessions#destroy'
  

  post 'first_contact/:address', to: "devices#first_contact"
  get  'first_contact/:address', to: "devices#first_contact"

  post 'sensor_data/batch_create/:device_address', to: 'sensor_data#batch_create'
  get 'sensor_data/batch_create/:device_address', to: 'sensor_data#batch_create'

  get 'buildings/:id/chart', to: 'buildings#chart'

  root 'pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
	validates :name, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A[A-Za-z0-9_]+\Z/ }
	has_many :devices
	has_many :buildings
	has_secure_password

	def user_id
		id
	end

	def admin?
		admin || false
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  force_ssl unless Rails.env.development? || Rails.env.test?
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :logged_out_redirect, only: [:new, :create]
  # GET /users
  # GET /users.json
  def index
    @users = policy_scope User.all.page params[:page]
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    authorize @user
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    authorize @user

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
    @buildings = policy_scope Building.where(user_id: @user.id)
    @devices = policy_scope Device.where(user_id: @user.id)
    authorize @user
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params[:user].permit(:name, :password, :password_confirmation, :admin)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_buildings_column.html.erb
<div>
	<h3>Active buildings:</h3>
	<table class="table">

	<tbody>
		<% @buildings.reverse.each do |building| %>
		<%if building.active? %>
		<tr>
			<th><h4><%= link_to building.name, building %></h4></th>
			<th>
				<%if building.in_violation %>
					<h4 style="color:red">Paramter Violation</h4>
				<% end %>
			</th>
		</tr>
		<tr>
			<td colspan="2">
			<table class="table">
				<thead>
					<tr>
						<th>Sensor</th>
						<th>Type</th>
						<th>Value</th>
						<th>Last Update</th>
					</tr>
				</thead>
				<tbody>
					<% building.sensors.each do |sensor| %>
					<tr>
						<td><%= link_to sensor.name, sensor %></td>
						<td> <%= sensor.sensor_type %> </td>
						<%if sensor.sensor_data.last %>
						<td <% if sensor.in_violation %> 
								style = "color:red" 
								<% else %>
								style = "color:green"
								<%end%>><%= sensor.sensor_data.last.data.to_s + sensor.unit%></td>
						<td><%= sensor.sensor_data.last.created_at.to_s(:custom) %></td>
						<% end %>
					</tr>
					<% end %>
				</tbody>	
			</table>
			</td>
		</tr>
		<% end %>
		<% end %>
	</tbody>
	</table>
	
</div>

<div class="center">
	<%= link_to "View all buildings", buildings_path %> <br><br>
	<%= link_to "Create new building", new_building_path %>
</div>

app/views/users/_devices_column.html.erb
<div>
	<h3>Devices:</h3>
	<table class="table">
		<thead>
			<th>Name</th>
			<th>Current building</th>
		</thead>
		<tbody>
	<% @devices.each do |device| %>
		<tr><td><%= link_to device.name, device %></td>
			<td>
			<%= device.in_building? ? link_to(device.building.name, device.building) : "None" %></td>
		</tr>
	<% end %>
	</tbody></table>

		<div class="center" style="margin-top:1em;">
			<%= link_to "View Devices", devices_path %>
		</div>

</div>

app/views/users/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation" style="margin:0 auto;">
    <h2>
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li> <%= msg %></li>
    <% end %>
    </ul>
  </div>
  <br>
<% end %>

app/views/users/_form.html.erb
<%# Expects local variables back_links & submit_name to be defined %>
<%= form_for(@user, html: { :class => "centered" }) do |f| %>
<%= render "error_messages" %>

<% if current_user.admin? %>

<div class="field">
	<%= f.label :name, "Username" %><br>
	<%= f.text_field :name %>
</div>
<div class="field">
	<%= f.label :admin %>
	<%= f.check_box :admin %>
</div>

<% else %>
<h3> <%=@user.name %> </h3>
<% end %>

<div class="field">
	<%= f.label :password %><br>
	<%= f.password_field :password %>
</div>

<div class="field">
	<%= f.label :password_confirmation, "Confirm Password" %><br>
	<%= f.password_field :password_confirmation %>
</div>
<div class="actions">
	<%= back_links %>
	<%= f.submit submit_name %>
</div>
<% end %>

app/views/users/edit.html.erb
<% provide :title, "Change password" %>

<%= render "form", back_links: link_to("Cancel", @user), submit_name: "Change password" %>

app/views/users/index.html.erb
<% provide :title, "Users" %>
<%= paginate @users %>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Buildings</th>
      <th>Sensors</th>
      <th>Admin?</th>
      <th colspan="3" class="options">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %> <%= " (you)" if current_user == user %></td>
        <td><%= user.buildings.count %></td>
        <td><%= user.devices.count %></td>
        <td><%= user.admin? ? "Admin" : "Normal user"%></td>
        <td><%= link_to 'Show', user, data: { no_turbolink: true } %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @users %>
<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide :title, "Sign up" %>

<%= render "error_messages" %>

<%= form_for(@user, html: { :class => "centered" }) do |f| %>

<div class="field">
	<%= f.label :name, "Username" %><br>
	<%= f.text_field :name %>
</div>

<div class="field">
	<%= f.label :password %><br>
	<%= f.password_field :password %>
</div>

<div class="field">
	<%= f.label :password_confirmation, "Confirm Password" %><br>
	<%= f.password_field :password_confirmation %>
</div>
<div class="actions">
	<%= f.submit "Create an account" %>
</div>
<% end %>

app/views/users/show.html.erb
<% provide :title, (@user == current_user) ? "Dashboard" : "User: " + @user.name %>


<div class="container-fluid">
	<div class="row">
		<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
	</div>
	<div class="row">
		<div class="col-sm-6">
			<%= render "buildings_column" %>
		</div>
		<div class="col-sm-6">
			<%= render "devices_column" %>

		</div>
		
	</div>

	<div class="row">
		<div class="col-sm-3">
			<%= link_to "Download all data as CSV", sensor_data_path(:format =>'csv') %>
		</div>
		<div class="col-sm-2 col-sm-offset-7">
			<%= link_to "Change password", edit_user_path(@user) %>
		</div>
	</div>

</div>