config/routes.rb
Rails.application.routes.draw do
  resources :sensors

  resources :buildings

  resources :sensor_data

  resources :devices

  resources :users

  resources :pages
  get 'home', to: 'pages#home'
  get 'faq', to: 'pages#faq'
  get 'buy', to: 'pages#buy'

  resources :sessions, only: [:create, :new]
  post 'sessions/destroy', to: 'sessions#destroy'
  get 'sessions/destroy', to: 'sessions#destroy'
  

  post 'first_contact/:address', to: "devices#first_contact"
  get  'first_contact/:address', to: "devices#first_contact"

  post 'sensor_data/batch_create/:device_address', to: 'sensor_data#batch_create'
  get 'sensor_data/batch_create/:device_address', to: 'sensor_data#batch_create'

  get 'buildings/:id/chart', to: 'buildings#chart'

  root 'pages#home'

end

app/models/building.rb
class Building < ActiveRecord::Base
	validates :name, presence: true

	has_many :sensor_data
	has_many :sensors
	#has_many :devices #Don't want to use direct connection
	has_many :device_buildings, dependent: :destroy

	has_many :devices, :through => :device_buildings
	accepts_nested_attributes_for :devices

	def active?
		if self.start.nil?
			return false
		end

		if (self.start <= Time.now)
			if (self.end.nil?) or (Time.now <= self.end)
				return true
			end
		end
		return false
	end


	def request_only_devices device_ids
		return if device_ids.nil?

		device_ids = device_ids.map { |e| e.to_i}

		self.device_buildings.each do |device_building|
			if device_ids.include? device_building.device_id
				device_ids -= [device_building.device_id]
			else
				#device_building.destroy
				Device.find(device_building.device_id).checkin(self.id)
			end
		end
		
		request_additional_devices device_ids
	end

	def request_additional_devices device_ids
		return if device_ids.nil?
		device_ids = device_ids.map { |e| e.to_i}

		new_devices = []
		device_ids.each do |id|
			device = Device.find(id)
			new_devices << device
		end

		self.devices << new_devices
	end

	def checkout_devices
		puts "checking out #{devices.count} devices"
		success = true
		self.devices.each do |device|
			device.checkout(self.id) rescue success = false
		end
		return success
	end

	def checkin_devices
		self.devices.each do |device|
			device.checkin(self.id) rescue return false
		end
		return true
	end

	def in_violation
		violated = false
		self.sensors.each do |sensor|
			if sensor.in_violation
				violated = true
			end
		end
		return violated
	end

	def self.to_csv
		csv = ""
		all.each do |building|
			csv << building.to_csv << "\n\n"
		end
		csv
	end

	def to_csv
		CSV.generate do |csv|
			#setting up headings
			csv << ["Building:",self.name, "Location:", self.location]
			csv << ["Start:", self.start.nil? ? "Not started" : self.start.in_time_zone.to_s(:custom_csv),
					"End:",   self.end.nil?   ? "Not ended" : self.end.in_time_zone.to_s(:custom_csv)]
			csv << [""]
			csv << ["Data"]

			chart_data = BuildingsHelper.chart_data(self, max_points: nil)
			csv << ["Time"] + (sensors.map {|x| x.name})
			chart_data.each do |time, values|
			row = [time.in_time_zone.to_formatted_s(:custom_csv)]
			values.sort_by!{|x| x.sensor_id}
			sensors.each do |sensor|
				if !values[0].nil? && values[0].sensor_id == sensor.id
					row << values.shift.data
				else
					row << nil
				end
			end
		csv << row
	end	
		end
	end

	#This is slightly less ugly than the other way to do this
	alias_method :super_update, :update
	private :super_update
	def update(params)
		if active? && params[:devices]
			if not checkout_devices
				return false
			end
		end
		super_update(params)
	end
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  force_ssl unless Rails.env.development? || Rails.env.test?
  before_action :set_building, only: [:show, :edit, :update, :destroy]
  # GET /buildings
  # GET /buildings.json
  def index
    @buildings = policy_scope Building.where(user_id: current_user.id).order(created_at: :desc).page(params[:page])
    respond_to do |format|
      format.html
      format.csv {
        send_data(@buildings.to_csv,
                  filename: "CO2_by_building_#{Time.zone.now}.csv",
                  disposition: 'inline', type: "multipart/related")
      }
    end
  end

  # GET /buildings/1
  # GET /buildings/1.json
  def show
    respond_to do |format|
      format.html
      format.csv {
        send_data @building.to_csv,
                  filename: "#{@building.id}-#{@building.name}.csv",
                  disposition: 'inline', type: "multipart/related"
      }
    end
  end

  # GET /buildings/new
  def new
    @building = Building.new(user_id: session[:current_user_id])
    @devices = policy_scope Device.where(user_id: current_user.id)
    authorize @building
  end

  # GET /buildings/1/edit
  def edit
  end

  # POST /buildings
  # POST /buildings.json
  def create
    @building = Building.new(building_params)
    authorize @building
    success = @building.save
    edit_helper()

    success &= @building.save

    respond_to do |format|

      if success
        format.html { redirect_to @building, notice: 'Building was successfully created.' }
        format.json { render :show, status: :created, location: @building }
      else
        format.html { @devices = policy_scope(Device.where(user_id: current_user.id)); render :new }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buildings/1
  # PATCH/PUT /buildings/1.json
  def update
    respond_to do |format|

      edit_helper()

      updated = @building.update(building_params)

      if updated
        format.html { redirect_to @building, notice: flash[:notice] || 'Building was successfully updated.' }
        format.json { render :show, status: :ok, location: @building }
      else
        format.html { render :edit, notice: 'Unable to update building.' }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1
  # DELETE /buildings/1.json
  def destroy
    @building.destroy
    respond_to do |format|
      format.html { redirect_to buildings_url, notice: 'Building was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def chart
    @building = Building.find(params[:id])
    authorize @building, :show?
    render :chart, formats: :csv
  end

  private

  def edit_helper
    success = true
    #Deals with special cases in forms

    #@building.request_only_devices(params[:building][:device_ids])
    @building.request_additional_devices(params[:building][:device_ids])
    if params[:building][:sensor_ids]
      Sensor.all.find(params[:building][:sensor_ids]).each do |sensor|
        sensor.activate(@building.id)
      end
    end
    puts "Params: #{params}"
    if params[:building][:start] == "now"
      if not @building.checkout_devices()
        success &= false
        flash[:notice] = "Unable to activate all sensors - some are in another building"
      end
      params[:building][:start] = Time.now
    end

    if params[:building][:end] == "now"
      @building.checkin_devices()
      params[:building][:end] = Time.now
    end


    #This code also smells...
    if params[:commit] == "Activate all"
      params[:building][:checkout] = "all"
    elsif params[:commit] == "Deactivate all"
      params[:building][:checkout] = "none"
    end

    if params[:building][:checkout] =="all"
      if not @building.checkout_devices()
        success &= false
        flash[:notice] = "Unable to activate all of the sensors - some are in another building"
      end
    elsif params[:building][:checkout]=="none"
      @building.checkin_devices()
    end

    #This code smells a bit...
    if params[:building][:device_buildings_locs] #locs is locations
      params[:building][:device_buildings_locs].each do |de_id, location|
        if de_id == "new" #Adds a location to the newly created device_building(s)
          params[:building][:device_buildings_locs][:new].each do |device_id, new_location|
            if de = DeviceBuilding.find_by(device_id: device_id, building_id: @building.id)
              de.location = new_location
              de.save
            end
          end
        else
          de = DeviceBuilding.find(de_id)
          de.location = location
          de.save
        end
      end
    end
    return success
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_building
    @building = Building.find(params[:id])
    authorize @building
    @devices = policy_scope Device.where(user_id: current_user.id)
    @sensors = policy_scope Sensor.where(user_id: current_user.id, activated: false)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def building_params
    params.require(:building).permit(:name, :location, :start, :end, :details,
                                     :co2_cutoff).merge(user_id: current_user.id)
    #{:device_ids => []}, # If this is included, ActiveRecord deletes the devices that don't have data submitted for them on update.
  end

end

app/helpers/buildings_helper.rb
module BuildingsHelper


	def self.chart_data building, options = {}
		#Options can have a :max_points field,
		# => which fetches the most recent :max_points pieces of data

		hash = {}
		building.sensor_data.order("created_at DESC").limit(options[:max_points]).each do |datum|

	  		if hash[datum.created_at].nil?
				hash[datum.created_at] = [ datum ]
			else
				hash[datum.created_at] << datum
			end
		end
		return hash.sort
	end

	def chart_data building, options
		BuildingsHelper.chart_data building, options
	end

end

app/views/buildings/_chart.html.erb
<div id="building_chart" style="margin-bottom: 30px;"></div>
<script>

new Dygraph(
  document.getElementById("building_chart"),
  "/buildings/<%=@building.id%>/chart.csv",
  { //Options
    connectSeparatedPoints: true, //Otherwise, buildings with multiple sensors are a mess

    width: false,
    height: 320,

    title: "<%= @building.name %>",
    ylabel: 'Value',
    xlabel: 'Time',


    //legend: "always",
    hideOverlayOnMouseOut:true,

    interactionModel : {},

    highlightCircleSize: 1,
    strokeWidth: .3,
    strokeBorderWidth: true ? null : .5,

    highlightSeriesOpts: {
      strokeWidth: .5,
      strokeBorderWidth: .5,
      highlightCircleSize: 2,
    },

    includeZero: false,

    drawPoints:true,
    pointSize:1,

    //labelsDiv: "chart_labels",
    labelsSeparateLines: true,
    yAxisLabelWidth:70,
    //xAxisLabelWidth: 100,
    xRangePad: 50,
    yRangePad: 50,
    axes: {
      x: {
        axisLabelFormatter: function(ms) {
                  return new Date(ms).strftime('%H:%M');
                }
      },

      y: {
        valueFormatter: function(value)
        {return value}
      },
    },

  })


</script>

app/views/buildings/_form.html.erb
<%# Expects local variable back_links to be defined %>
<%# This script probably shouldn't be here... %>
<script type="text/javascript">
var check_box_change = function(device_id) {
  var check_box = document.querySelector("input[type='checkbox'][value='"+ device_id + "']");
  var location = document.querySelector("#location_for_device_" + device_id);

  if(check_box.checked && location != null) {
     location.style['visibility'] = 'visible';
  } else {
    location.style['visibility'] = 'hidden';
  }
}
</script>

<script type="text/javascript">
var sensor_check_box_change = function(sensor_id) {
  var check_box = document.querySelector("input[type='checkbox'][value='"+ device_id + "']");
  var location = document.querySelector("#location_for_sensor_" + sensor_id);
}
</script>

<%= form_for(@building , html: {:class => "centered"}) do |f| %>
  <% if @building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
      <% @building.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= render "application/tooltip", tooltip: "The location of the building.", visible: f.label(:location, "Building Location") %><br>
    <%= f.text_field :location %>
  </div>


<% if not @building.start.nil? %>
  <div class="field">
    <%= f.label :start %><br>
    <%= f.datetime_select :start, ampm: true%>
  </div>
<% end %>

<% if not @building.end.nil? %>
  <div class="field">
    <%= f.label :end %><br>
    <%= f.datetime_select :end, ampm: true %>
  </div>
<% end %>

  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_area :details%>
  </div>

<div>
  <% if @sensors %>
  <table class="table">
    <thead>
    <tr>
      <th> Sensor </th>
      <th></th>
      <th> Sensor ID </th>
      <th> Channel </th>
      <th> Location </th>
      </tr>
    </thead>
    <tbody>
    <% @sensors.each do |sensor| %>
    <tr>
    
      <td>
        <%= fields_for(sensor) do |sensor_f| %>
      <% checked = @building.sensors.include?(sensor) %>
      <%= sensor_f.label sensor.name %>
      </td>
      <td>
        <%= check_box_tag("building[sensor_ids][]", sensor.id, checked, onchange: "sensor_check_box_change(#{sensor.id.to_s})", disabled: checked) %>
      </td>
      <td> <%= sensor.sensor_id %></td>
      <td> <%= sensor.channel %></td>
      <td> todo </td>
      <% end %>
    
    </tr>
    <% end %>
    </tbody>
  </table>
  <% else %>
    <p> There Are no Sensors.</p>
    <p>Try <%= link_to "Create Sensor", new_sensor_path %></p>
  <% end %>
</div>

<div>
  <br>
  <% if @devices %>
  <table class="table">
    <thead>
      <th><%= f.label :devices, "Device" %><th></th></th><th><%= render "application/tooltip", visible: "Device Location", tooltip: "Where the device is in the building."%></th>
    </thead>
    <tbody>
      <% @devices.each do |device| %>
      <tr>
        <td>
      <%= fields_for(device) do |device_f| %>
      <% checked = @building.devices.include?(device) %>
      <%= device_f.label device.name %>
        </td>
        <td>
          <%= check_box_tag("building[device_ids][]", device.id, checked, onchange: "check_box_change(#{device.id.to_s})", disabled: checked) %>
        </td>
          <% de = DeviceBuilding.find_by(building_id: @building.id, device_id: device.id) %>

          <% if !de.nil? %>
            <td>
            <%= fields_for(de) do |de_f| %>
              <%= text_field_tag("building[device_buildings_locs][#{de.id}]", de.location )%>
            <% end %>
            </td>
          <% else %>
            <% display_location = checked ? "visible" : "hidden" %>
            <td style='visibility:<%= display_location %>', id='<%= 'location_for_device_' + device.id.to_s %>'>
              <%= text_field_tag("building[device_buildings_locs][new][#{device.id}]", "", { placeholder: "Add a location"}) %>
            </td>
          <% end %>


      <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
  <% else %>
  <p>There appear to be no devices available.</p>
  <% end %>
</div>

  <div class="actions">
    <%= back_links %>
    <%= f.submit %>
  </div>
<% end %>

app/views/buildings/_form_all_devices.html.erb
<div style="float:left; display:inline-block" class="container">
<%= form_for(@building) do |f| %>

  <div class="field">
    <%= f.hidden_field :checkout, :value => "?"%>
  </div>

  <table><tr>
    <td class="actions">
      <%= f.submit "Deactivate all", onclick: "return confirm('Are you sure you want to deactivate all sensors?');" %>
    </td>

    <td class="actions">
      <%= f.submit "Activate all" %>
    </td>

  <td>
    <%= render "application/tooltip", tooltip: "Activating sensors tells them to start collecting data." %>
  </td>
  </tr></table>
<% end %>
</div>
<br>

app/views/buildings/_form_device.html.erb
<%# Expects device and building_id to be defined%>
<%    
    disabled = false
    if device.building_id == building_id
      label = "Deactivate"
      value = nil
      form_html = "return confirm('Are you sure you want to deactivate this device?');"
    else
      label = "Activate"
      value = @building.id
      form_html = ""

      if device.in_building?
        label = "Unavailable"
        disabled = true
      end
    end

    %>

<%= form_for(device, html: { :onsubmit => form_html }) do |f| %>
 <% if device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.hidden_field :redirect_to, :value => '/buildings/' + building_id.to_s %>
    <%= f.hidden_field :building_id, :value => value%>
  </div>

  <div class="actions" style="margin:0">
    <%= f.submit label, disabled: disabled %>
  </div>

<% end %>

app/views/buildings/_form_reopen.html.erb
<%= form_for(@building) do |f| %>
 <% if @building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
      <% @building.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :end, :value => "nil"%>
  </div>

  <div class="actions">
    <%= f.submit "Re-Start Monitoring" %>
  </div>

<% end %>

app/views/buildings/_form_start.html.erb
<%= form_for(@building) do |f| %>
 <% if @building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
      <% @building.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :start, :value => "now"%>
  </div>

  <div class="actions">
    <%= f.submit "Start Monotoring" %>
  </div>

<% end %>

app/views/buildings/_show_devices.html.erb
<% if not @building.device_buildings.first.nil? %>
<%# If there is any devices attached to the building %>
<p>
  <table class="table">
<thead><tr>
  <th><strong>Devices</strong></th> <th></th> <th><%= render "application/tooltip", visible: "Device Location", tooltip: "Where the device is in the building."%> </th><tr>
</thead>
<tbody>
	<% @building.device_buildings.each do |de| %>
		<tr><td><%= link_to de.device.name, de.device %>
        </td>
        <td><%= render 'form_device', device: de.device, building_id: @building.id if @building.active? %></td>
        <td> <%= de.location %> </td>
    </tr>
	<% end %>
</tbody>
</table>
<%= render 'form_all_devices' if @building.active? %>

</p>
<% else %>
<p><br>This building doesn't appear to have any devices.</p>
<% end %>

app/views/buildings/_show_sensors.html.erb
<% if not @building.sensors.first.nil? %>
<%# If there is any devices attached to the building %>
<p>
  <table class="table">
<thead><tr>
  <th><strong>Sensors</strong></th> <th><strong>Latest Value</strong></th> <th><strong>Time Updated</strong></th><tr>
</thead>
<tbody>
	<% @building.sensors.each do |de| %>
		<tr><td><%= link_to de.name, de %>
        </td>
        <td><%=  de.sensor_data.last.data if de.sensor_data.last %></td>
        <td><%= de.sensor_data.last.created_at.to_s(:custom) if de.sensor_data.last %></td>
    </tr>
	<% end %>
</tbody>
</table>


</p>
<% else %>
<p><br>This building doesn't appear to have any sensors.</p>
<% end %>

app/views/buildings/_show_start_and_end.html.erb
<% if @building.start.nil? %>
  	<div>
  		<%= render 'form_start' %>
<% elsif @building.end.nil? %>
  <p>
    <strong>Start:</strong>
    <%= @building.start.in_time_zone.to_s(:custom) %>
  </p>
  <p>
  	<div>
  		<%= render 'form_end' %>
  	</div>

<% else %>
  <p>
    <strong>Start:</strong>
    <%= @building.start.in_time_zone.to_s(:custom) %>
  </p>
  <p>
    <strong>End:</strong>
  	<%= @building.end.in_time_zone.to_s(:custom) %>
  </p>
  <p>
    <div>
      <%= render 'form_reopen' %>
    </div>
  </p>
<% end %>

app/views/buildings/chart.csv.erb
<% @sensors = @building.sensors.all %>
<%=
CSV.generate do |csv|
	csv << ["Time"] + (@sensors.map {|x| x.name})
	chart_data(@building, max_points: 10000).each do |time, values|
		row = [time.in_time_zone.to_formatted_s(:custom_csv)]
		values.sort_by!{|x| x.sensor_id}
		@sensors.each do |sensor|
			if !values[0].nil? && values[0].sensor_id == sensor.id
				row << values.shift.data
			else
				row << nil
			end
		end
		csv << row
	end	
end
%>

app/views/buildings/edit.html.erb
<% provide :title, "Edit building" %>

<%= render 'form', back_links: (link_to('Show', @building) + " | " + link_to('Cancel', buildings_path)) %>

app/views/buildings/index.html.erb
<% provide :title, "Buildings" %>

<p>
  Download all:
  <%= link_to "CSV", buildings_path(format: "csv") %>
</p>
<p>
  A building is made up of one or more Devices which report the status of sensors that are attached to them. Buildings are mostly comprised of sensors, through devices, which report information to the building.
</p>
<%= paginate @buildings %>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Status</th>
      <th>Download</th>
      <th colspan="2" class="options">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @buildings.each do |building| %>
      <tr>
        <td><%= link_to building.name, building %></td>
        <td><%= building.location %></td>
        <td><%= if building.active?
                  "Monitoring"
                else
                  "Not Monotoring"
                end %></td>
        <td><%= link_to "CSV", :action => :show, :id => building.id, :format =>'csv'%></td>
        <td><%= link_to 'Edit', edit_building_path(building) %></td>
        <td><%= link_to 'Destroy', building, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @buildings %>
<br>

<%= link_to 'New building', new_building_path %>

app/views/buildings/new.html.erb
<% provide :title, "New building" %>
	<%= render 'form', back_links: link_to('Cancel', buildings_path) %>

app/views/buildings/show.html.erb
<% provide :title, "Building View" %>

<p>
  Download:
  <%= link_to "CSV", :action => :show, :id => @building.id, :format =>'csv'%>

</p>

 <% if @building.sensor_data.empty? %>
 <br>
 <p>This building has no data yet.

 <% if @building.active? %>
 <%# Not printing anything %>
 <% elsif @building.start.nil? %>
 Press Start building to begin collecting data.
 <% elsif !@building.end.nil?%> <%#should be true %>
 <br>
 Reopen building or wait for data to upload from already active sensors to add data.
 <% end %>
 </p>
 <% else %>
  <%= render 'chart' %>
 <% end %>

<br>
<p>
	<strong>Name:</strong>
	<%= @building.name %>
</p>

<p>
	<%= render "application/tooltip", tooltip: "The building and room where the building takes place.", visible: "<strong>Building Location:</strong>" %>
  <%= @building.location %>
</p>


<%= render 'show_start_and_end' %>

<div>
<strong>Details:</strong>
<pre><%= @building.details %></pre>
<br>
</div>

<%= render 'show_sensors' %>
<%= render 'show_devices' %>

<br>
<%= link_to 'Back', buildings_path %> | 
<%= link_to 'Edit', edit_building_path(@building) %>