config/routes.rb
Rails.application.routes.draw do
  resources :sensors

  resources :buildings

  resources :sensor_data

  resources :devices

  resources :users

  resources :pages
  get 'home', to: 'pages#home'
  get 'faq', to: 'pages#faq'
  get 'buy', to: 'pages#buy'

  resources :sessions, only: [:create, :new]
  post 'sessions/destroy', to: 'sessions#destroy'
  get 'sessions/destroy', to: 'sessions#destroy'
  

  post 'first_contact/:address', to: "devices#first_contact"
  get  'first_contact/:address', to: "devices#first_contact"

  post 'sensor_data/batch_create/:device_address', to: 'sensor_data#batch_create'
  get 'sensor_data/batch_create/:device_address', to: 'sensor_data#batch_create'

  get 'buildings/:id/chart', to: 'buildings#chart'

  root 'pages#home'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<row>
		<div class="col-xs-2 pull-left">
		<% if current_user.nil? %>
			<%= link_to "Login", { :controller => "sessions", :action => "new" } %>
		<% else %>
			<%= link_to "Logout", { :controller => "sessions", :action => :destroy }, :disabled => current_user.nil? %>
		<% end %>
		</div>


		<div class="col-xs-2 pull-right"><small>
			<a href="http://wickeddevice.com">Wicked Device</a>
		</small></div>

	</row>

	<% if current_user && current_user.admin? %>
		<row class="nav">
			<ul class="col-sm-6">
				<li>Admin links:</li>
				<li><%= link_to "Sensor Data", sensor_data_path %></li>

				<li><%= link_to "Users", users_path %></li>

				<li><%= link_to "Pages", pages_path %></li> 
			</ul>
		</row>
	<% end %>

</footer>

app/views/layouts/_header.html.erb
<% #This code should probably not be right here
if current_user.nil?
	user_button = link_to("Login", { :controller => "sessions", :action => "new" })
	ul_class = "nav navbar-right navbar-nav navbar-custom"
else
	user_button = link_to(current_user.name, current_user)
	ul_class = "nav navbar-collapse collapse navbar-right navbar-nav navbar-custom"
end %>

<header id="navbar" class="navbar navbar-fixed-top navbar-custom">
	<div class="navbar-inner">
		<div class="container">
			<div class="navbar-header">

				<div id='logo'>
					<%= link_to image_tag("wicked_device_logo.jpg"), "http://wickeddevice.com" %>
					<%= link_to "Home", root_path %>
				</div>

				<div id="title-small" class="nav navbar-nav nav-center title">
					<%= content_for(:navbar_title) || yield(:title) %>
				</div>

				<% unless current_user.nil? %>
				<button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse" type="button">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<% end %>
			</div>

			<div>
				<div id="title-large" class="nav navbar-nav nav-center title">
					<%= content_for(:navbar_title) || yield(:title) %>
				</div>
				<ul class="<%= ul_class%>" >
					<li><%= link_to "FAQ", controller: :pages, :action => :faq %></li>
					<li><%= link_to "Buy", controller: :pages, :action => :buy %></li>
					<% unless current_user.nil? %>
					<li><%= link_to "Devices", devices_path %></li>
					<li><%= link_to "Sensors", sensors_path %></li>
					<li><%= link_to "Buildings", buildings_path %></li>
					<% end %>
					<li class="divider-vertical"></li>
					<li><%= user_button %>
				</ul>
			</div>
		</div>
	</div>
</header>
<br>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <% if content_for? :title %>
  <title>HomeMonitor | <%= yield :title %></title>
  <% else %>
  <title>HomeMonitor</title>
  <% end %>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  </head>
  <body class="<%= controller_name %> <%= action_name %> <%= content_for(:body_class) %>" style="<%= yield :body_style %>">
	<%= render 'layouts/header' %>
	<div class="container <%= yield :container_class %>">
    <% flash.each do |key, value| %>
      <% key = "info" if key =="notice"
         key = "danger" if key =="errors" || key =="error" %>
      <div class="alert alert-<%= key %> alert-dismissable">
        <%= value %>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      </div>
    <% end %>
		<%= yield %>
	</div>
	<%= render 'layouts/footer' %>
  </body>
</html>